### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by pashtika** [Fruzenshtein/spr-data#6]
I suspect you need to add following dependency in pom.xml file, otherwise it will give JSP compilation error.
`<dependency>
		<groupId>javax.servlet.jsp</groupId>
		<artifactId>jsp-api</artifactId>
		<version>2.2</version>
</dependency>
`
Also could you please create same example to use xml configurations instead of java beans ?

**Comment by Fruzenshtein** [comment]
If you run the app inside of Tomcat you do not need this dependency, since Tomcat includes it.
