### ISSUE TITLE
how to run this app

### ISSUE THREAD

**Issue by klaus20141002** [Fruzenshtein/spr-data#9]
i check out this app to my computor, compile it , but i can not run this app on tomcat , error message as below
Caused by: java.lang.ClassNotFoundException: org.hibernate.service.jndi.JndiException
as i know this is case of dependency conflict , but i do not know how to fix this , please help .

my email is :love20141002@126.com

Best Regards

Niklaus Mikaelson

**Comment by Fruzenshtein** [comment]
http://fruzenshtein.com/spring-jpa-data-hibernate-mysql

Read here
